// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6i9PL-jqvvWlT-AzEu3wFbvZ0zEsLAk',
    appId: '1:741317622910:web:2f85281205a7e9192aec2f',
    messagingSenderId: '741317622910',
    projectId: 'bookshelf-ef677',
    authDomain: 'bookshelf-ef677.firebaseapp.com',
    storageBucket: 'bookshelf-ef677.firebasestorage.app',
    measurementId: 'G-9PES7E70RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOXQ7Emjdwzvu-0UnFKDJovOF59w07zI',
    appId: '1:741317622910:android:c61dfde22791384b2aec2f',
    messagingSenderId: '741317622910',
    projectId: 'bookshelf-ef677',
    storageBucket: 'bookshelf-ef677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD_shfcaRfdkWrfb1lxYImwa_k9RQ5DPg',
    appId: '1:741317622910:ios:cd2722fe6226f1632aec2f',
    messagingSenderId: '741317622910',
    projectId: 'bookshelf-ef677',
    storageBucket: 'bookshelf-ef677.firebasestorage.app',
    iosBundleId: 'com.example.bookselfApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD_shfcaRfdkWrfb1lxYImwa_k9RQ5DPg',
    appId: '1:741317622910:ios:cd2722fe6226f1632aec2f',
    messagingSenderId: '741317622910',
    projectId: 'bookshelf-ef677',
    storageBucket: 'bookshelf-ef677.firebasestorage.app',
    iosBundleId: 'com.example.bookselfApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc6i9PL-jqvvWlT-AzEu3wFbvZ0zEsLAk',
    appId: '1:741317622910:web:7ccd0312bc65d0a12aec2f',
    messagingSenderId: '741317622910',
    projectId: 'bookshelf-ef677',
    authDomain: 'bookshelf-ef677.firebaseapp.com',
    storageBucket: 'bookshelf-ef677.firebasestorage.app',
    measurementId: 'G-2PXMFZHW78',
  );
}
