name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-13   # stick to macOS 13 for stable builds

    steps:
      - uses: actions/checkout@v3

      # ✅ Force GitHub to use Xcode 14.3.1 (Swift 5.8) instead of Xcode 15+
      - name: Select Xcode 14.3.1
        run: sudo xcode-select -s "/Applications/Xcode_14.3.1.app"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod install --repo-update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir -p Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
